name: CI

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install
        run: yarn install --immutable
      - name: Run
        run: node .
